import type { ElementType } from 'react';
import {
  Activity,
  BadgeCheck,
  BadgeInfo,
  Banknote,
  Bell,
  BellDot,
  BellRing,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Boxes,
  Briefcase,
  Building2,
  Bus,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ChartColumn,
  ChartLine,
  ChartPie,
  CircleAlert,
  CircleMinus,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  ClipboardPen,
  Clock,
  CreditCard,
  Download,
  FileBadge,
  FileCheck,
  FilePen,
  FileSpreadsheet,
  FileText,
  Files,
  Film,
  Fingerprint,
  FolderOpen,
  Gauge,
  Gavel,
  GitBranch,
  GitFork,
  GraduationCap,
  HandHelping,
  Heart,
  HeartHandshake,
  HeartPulse,
  House,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Library,
  LibraryBig,
  LifeBuoy,
  ListTodo,
  LockOpen,
  Mail,
  MailPlus,
  MapPinned,
  Megaphone,
  MessageCircle,
  MessageCircleMore,
  MessageSquare,
  MessagesSquare,
  MonitorPlay,
  Network,
  NotebookPen,
  Package,
  Palette,
  PenLine,
  Percent,
  Plug,
  Presentation,
  Radio,
  Receipt,
  ReceiptText,
  Rocket,
  Scale,
  ScanLine,
  School,
  ScrollText,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  SmilePlus,
  Sparkles,
  Stamp,
  TableProperties,
  TriangleAlert,
  Trophy,
  Upload,
  UserCog,
  UserPen,
  UserPlus,
  UserRoundCheck,
  UserX,
  Users,
  UsersRound,
  Video,
  Wallet,
  Warehouse,
  Workflow,
} from 'lucide-react';

export const NAV_ICONS = {
  dashboard: LayoutDashboard,
  school: School,
  people: Users,
  admissions: UserPlus,
  academics: BookOpen,
  assessment: ClipboardCheck,
  performance: ChartLine,
  attendance: CalendarCheck,
  finance: Wallet,
  communication: MessagesSquare,
  'online-learning': MonitorPlay,
  'student-services': HeartHandshake,
  operations: Warehouse,
  administration: ShieldCheck,
  subscription: BadgeCheck,
  reports: ChartPie,
  help: LifeBuoy,

  'school-profile': Landmark,
  branding: Palette,
  campuses: MapPinned,
  sessions: CalendarRange,
  terms: CalendarDays,
  classes: LayoutGrid,
  arms: GitBranch,
  departments: Network,
  'school-subjects': BookMarked,
  houses: House,
  facilities: Building2,
  'academic-calendar': CalendarClock,

  students: GraduationCap,
  teachers: Presentation,
  staff: Briefcase,
  parents: UsersRound,
  administrators: UserCog,
  'user-accounts': CircleUser,
  invitations: MailPlus,
  'bulk-import': Upload,

  curriculum: Library,
  'academic-subjects': BookOpen,
  'class-allocation': LayoutList,
  'teacher-allocation': UserPen,
  timetable: CalendarClock,
  lessons: NotebookPen,
  'scheme-of-work': ListTodo,
  'learning-resources': FolderOpen,

  'continuous-assessment': ClipboardList,
  tests: FilePen,
  examinations: FileBadge,
  'question-bank': LibraryBig,
  'exam-scheduling': CalendarClock,
  'marks-entry': PenLine,
  'manual-assessment': ClipboardPen,
  smartmark: ScanLine,
  'grade-configuration': Settings2,
  results: Trophy,
  'report-cards': FileText,
  'result-approval': Stamp,
  'result-publishing': Send,
  'result-pins': KeyRound,

  'student-progress': ChartLine,
  'subject-performance': BookOpenCheck,
  'class-performance': ChartColumn,
  'performance-trends': ChartLine,
  'at-risk-students': TriangleAlert,
  'intervention-tracking': HeartPulse,
  'ai-performance': Sparkles,

  'student-attendance': CalendarCheck,
  'staff-attendance': UserRoundCheck,
  'daily-register': ClipboardCheck,
  'absence-management': UserX,
  'late-arrivals': Clock,
  'attendance-analytics': ChartColumn,
  'attendance-summary': FileSpreadsheet,
  biometrics: Fingerprint,
  'attendance-notifications': BellRing,

  'fee-structure': TableProperties,
  'student-billing': Receipt,
  invoices: FileSpreadsheet,
  payments: Banknote,
  'outstanding-fees': CircleAlert,
  discounts: Percent,
  scholarships: Trophy,
  'payment-plans': CalendarClock,
  receipts: ReceiptText,
  expenses: CircleMinus,
  'financial-reports': ChartPie,
  reconciliation: Scale,

  announcements: Megaphone,
  notices: Bell,
  'parent-messages': MessageCircle,
  'teacher-messages': MessageSquare,
  'student-messages': MessageCircleMore,
  email: Mail,
  sms: Smartphone,
  'push-notifications': BellDot,
  broadcasts: Radio,

  'virtual-classes': Video,
  'live-lessons': MonitorPlay,
  'recorded-lessons': Film,
  'online-materials': FolderOpen,
  assignments: FileCheck,
  discussions: MessagesSquare,
  cbt: LibraryBig,

  behaviour: SmilePlus,
  discipline: Gavel,
  welfare: Heart,
  counselling: HeartHandshake,
  library: Library,
  transport: Bus,
  'student-support': HandHelping,

  assets: Package,
  inventory: Boxes,
  'operations-facilities': Building2,
  approvals: Stamp,
  documents: Files,
  'operational-reports': ClipboardList,

  'roles-permissions': KeyRound,
  'user-access': Shield,
  'workflow-rules': GitFork,
  automation: Workflow,
  integrations: Plug,
  'audit-logs': ScrollText,
  security: ShieldCheck,
  'auth-policies': Fingerprint,
  'system-configuration': Settings,
  'school-settings': School,
  schools: Building2,
  health: Activity,
  governance: Scale,

  'current-plan': BadgeCheck,
  usage: Gauge,
  billing: CreditCard,
  'subscription-invoices': FileSpreadsheet,
  entitlements: LockOpen,
  upgrade: Rocket,

  'academic-reports': BookOpen,
  'attendance-reports': CalendarCheck,
  'student-reports': GraduationCap,
  'staff-reports': Briefcase,
  'finance-reports': Wallet,
  'admission-reports': UserPlus,
  'performance-reports': ChartLine,
  'custom-reports': SlidersHorizontal,
  'export-centre': Download,

  'help-support': LifeBuoy,
  'school-info': BadgeInfo,
} as const;

export type NavIconKey = keyof typeof NAV_ICONS;

export function navIcon(key: string | undefined): ElementType {
  if (key && key in NAV_ICONS) {
    return NAV_ICONS[key as NavIconKey];
  }
  return LayoutDashboard;
}
