import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Eye, FilePenLine, ListChecks, MoreHorizontal, Pencil, Plus, Search } from 'lucide-react';
import { apiMutation, apiRequest, describeApiError } from '../../lib/apiClient';
import { useApp } from '../../context/AppContext';
import { Modal } from '../../components/ui/Modal';

interface PlanningRecord { id: string; title: string; status: string; payload: Record<string, string>; updatedAt?: string }
type PlanningKind = 'scheme' | 'lesson';

const config = {
  scheme: { module: 'scheme-of-work', title: 'Scheme of Work', singular: 'Scheme', statuses: ['draft','submitted','under_review','approved','returned'] },
  lesson: { module: 'lesson-plans', title: 'Lesson Plans', singular: 'Lesson Plan', statuses: ['draft','submitted','under_review','approved','returned'] },
} as const;

export const AcademicPlanningManager: React.FC<{ kind: PlanningKind; openSignal?: number }> = ({ kind, openSignal = 0 }) => {
  const { subjects, classes, terms, staff, showToast } = useApp();
  const meta = config[kind];
  const [rows, setRows] = useState<PlanningRecord[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState<PlanningRecord | null>(null); const [viewing, setViewing] = useState<PlanningRecord | null>(null); const [open, setOpen] = useState(false);
  const empty = { title:'', subject:'', class:'', term:'', teacher:'', week:'', topics:'', completed_topics:'0', notes:'', status:'draft' };
  const [form, setForm] = useState<Record<string,string>>(empty);
  const load = async () => { setLoading(true); try { const r = await apiRequest<{data:{data:PlanningRecord[]}}>(`/school-modules/${meta.module}`, { suppressErrorNotification:true }); setRows(r.data.data); } catch(e) { showToast(meta.title, describeApiError(e), 'error'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [kind]);
  useEffect(() => { if (openSignal) startCreate(); }, [openSignal]);
  const startCreate = () => { setEditing(null); setForm({...empty, term:terms.find(t=>t.isCurrent)?.name || '', teacher:kind === 'lesson' ? staff.find(s=>s.role==='Teacher')?.fullName || '' : ''}); setOpen(true); };
  const startEdit = (row:PlanningRecord) => { setEditing(row); setForm({...empty,...row.payload,title:row.title,status:row.status}); setOpen(true); };
  const filtered = useMemo(() => rows.filter(r => `${r.title} ${Object.values(r.payload).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [rows,query]);
  const submit = async (e:React.FormEvent) => { e.preventDefault(); setBusy(true); const payload = {...form}; delete payload.title; delete payload.status; try { const path = editing ? `/school-modules/${meta.module}/${editing.id}` : `/school-modules/${meta.module}`; await apiMutation(path, editing ? 'PATCH':'POST', { title:form.title, status:form.status, payload }); showToast(`${meta.singular} saved`, editing ? 'Changes were saved.' : 'The record was created.', 'success'); setOpen(false); await load(); } catch(error) { showToast(`Could not save ${meta.singular.toLowerCase()}`, describeApiError(error), 'error'); } finally { setBusy(false); } };
  const setStatus = async (row:PlanningRecord,status:string) => { try { await apiMutation(`/school-modules/${meta.module}/${row.id}`,'PATCH',{status}); showToast('Status updated', `${row.title} is now ${status.replaceAll('_',' ')}.`, 'success'); load(); } catch(e) { showToast('Could not update status',describeApiError(e),'error'); } };
  const fields = kind === 'scheme' ? [['subject','Subject'],['class','Class'],['term','Term'],['teacher','Teacher'],['topics','Total topics'],['completed_topics','Completed topics']] : [['teacher','Teacher'],['subject','Subject'],['class','Class'],['term','Term'],['week','Week'],['topics','Topic']];
  return <div className="space-y-4">
    <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-bold text-slate-900">{meta.title}</h2><p className="mt-1 text-xs text-slate-500">{rows.length} record{rows.length===1?'':'s'} for the academic workspace</p></div><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search planning…" className="h-9 rounded-xl border border-slate-200 pl-9 pr-3 text-xs"/></label><button onClick={startCreate} className="inline-flex h-9 items-center gap-2 rounded-xl bg-indigo-700 px-4 text-xs font-bold text-white"><Plus className="h-4 w-4"/>Create {meta.singular}</button></div></div>
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="border-b bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500">{(kind==='scheme'?['Title','Subject','Class','Term','Teacher','Topics','Status','Actions']:['Title','Teacher','Subject','Class','Week','Term','Status','Actions']).map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{loading && <tr><td colSpan={8} className="p-10 text-center text-slate-500">Loading planning records…</td></tr>}{!loading && !filtered.length && <tr><td colSpan={8} className="p-12 text-center"><div className="mx-auto mb-3 w-fit rounded-xl bg-indigo-50 p-3 text-indigo-600">{kind==='scheme'?<ListChecks className="h-5 w-5"/>:<FilePenLine className="h-5 w-5"/>}</div><b className="text-slate-800">No {meta.title.toLowerCase()} found</b><p className="mt-1 text-slate-500">Create the first record to begin the planning workflow.</p></td></tr>}{filtered.map(r=>{const p=r.payload; const cells=kind==='scheme'?[r.title,p.subject,p.class,p.term,p.teacher,`${p.completed_topics||0}/${p.topics||0}`]:[r.title,p.teacher,p.subject,p.class,p.week,p.term]; return <tr key={r.id} className="border-b border-slate-100 hover:bg-slate-50">{cells.map((c,i)=><td key={i} className={`px-4 py-3 ${i===0?'font-bold text-slate-900':'text-slate-600'}`}>{c||'—'}</td>)}<td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${r.status==='approved'?'bg-emerald-50 text-emerald-700':r.status==='returned'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'}`}>{r.status.replaceAll('_',' ')}</span></td><td className="px-4 py-3"><div className="flex gap-1"><button title="View" onClick={()=>setViewing(r)} className="rounded-lg p-2 hover:bg-slate-100"><Eye className="h-4 w-4"/></button><button title="Edit" onClick={()=>startEdit(r)} className="rounded-lg p-2 hover:bg-slate-100"><Pencil className="h-4 w-4"/></button>{r.status!=='approved'&&<button title="Approve" onClick={()=>setStatus(r,'approved')} className="rounded-lg p-2 text-emerald-600 hover:bg-emerald-50"><CheckCircle2 className="h-4 w-4"/></button>}</div></td></tr>})}</tbody></table></div>
    <Modal isOpen={open} onClose={()=>setOpen(false)} size="lg" title={`${editing?'Edit':'Create'} ${meta.singular}`} description="Complete the academic context and workflow status." footer={<><button onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2 text-xs font-bold">Cancel</button><button form="planning-form" disabled={busy} className="rounded-xl bg-indigo-700 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{busy?'Saving…':'Save record'}</button></>}><form id="planning-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Title" required><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="field" placeholder={`${meta.singular} title`}/></Field>{fields.map(([key,label])=><Field key={key} label={label} required={['subject','class','term','teacher','topics'].includes(key)}>{key==='subject'?<select required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="field"><option value="">Select subject</option>{subjects.map(x=><option key={x.id}>{x.name}</option>)}</select>:key==='class'?<select required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="field"><option value="">Select class</option>{classes.map(x=><option key={x.id}>{x.name}</option>)}</select>:key==='term'?<select required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="field"><option value="">Select term</option>{terms.map(x=><option key={x.id}>{x.name}</option>)}</select>:key==='teacher'?<select required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="field"><option value="">Select teacher</option>{staff.filter(x=>x.role==='Teacher').map(x=><option key={x.id}>{x.fullName}</option>)}</select>:<input required={['topics'].includes(key)} type={['topics','completed_topics','week'].includes(key)?'number':'text'} min="0" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="field"/>}</Field>)}<Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="field">{meta.statuses.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></Field><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-bold text-slate-700">Notes / learning objectives</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={5} className="field"/></label></form></Modal>
    <Modal isOpen={!!viewing} onClose={()=>setViewing(null)} title={viewing?.title || ''} description={`${meta.singular} details`}><dl className="grid gap-4 sm:grid-cols-2">{viewing&&Object.entries(viewing.payload).filter(([,v])=>v).map(([k,v])=><div key={k}><dt className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{k.replaceAll('_',' ')}</dt><dd className="mt-1 whitespace-pre-wrap text-sm text-slate-800">{v}</dd></div>)}</dl></Modal>
  </div>;
};
const Field: React.FC<{label:string;required?:boolean;children:React.ReactNode}> = ({label,required,children})=><label><span className="mb-1.5 block text-xs font-bold text-slate-700">{label}{required&&<span className="text-rose-500"> *</span>}</span>{children}</label>;
