import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { BookOpen, Building, Building2, CalendarDays, CalendarRange, ChevronRight, Download, Filter, GitBranch, Mail, MapPin, MoreHorizontal, Network, Palette, Pencil, Phone, Plus, Search, School, Settings2, Shield, UsersRound } from 'lucide-react';
import { apiMutation, apiRequest, describeApiError } from '../../lib/apiClient';
import { useApp } from '../../context/AppContext';
import { BrandMark } from '../../components/BrandMark';
import { Button, Drawer, Modal, StatusBadge } from '../../components/ui';
import { BrandingStudio } from '../branding/BrandingStudio';

interface Props { resource: string; title: string }
type Row = Record<string, any>;
type StructureKey = 'campuses' | 'departments' | 'sessions' | 'classes' | 'arms' | 'subjects';
type ModuleKey = 'houses' | 'facilities' | 'calendar';
const structureKeys: StructureKey[] = ['campuses', 'departments', 'sessions', 'classes', 'arms', 'subjects'];
const allKeys = [...structureKeys, 'houses', 'facilities', 'calendar'];
const labels: Record<string, string> = { campuses: 'Campuses', departments: 'Departments', sessions: 'Academic years', terms: 'Terms', classes: 'Classes & streams', arms: 'Streams', subjects: 'Subjects', houses: 'Houses', facilities: 'Facilities', calendar: 'Calendar' };
const fields: Record<string, string[]> = { campuses: ['name','code'], departments: ['name','code'], sessions: ['name','startsAt','endsAt'], terms: ['sessionId','name','sequence','startsAt','endsAt'], classes: ['name','arm','capacity'], arms: ['name'], subjects: ['name','code'], houses: ['name','color','houseMaster'], facilities: ['name','type','campus','capacity'], calendar: ['name','date','category','scope'] };
const icons: Record<string, React.ElementType> = { campuses: Building2, departments: Network, sessions: CalendarRange, classes: UsersRound, arms: GitBranch, subjects: BookOpen, houses: Shield, facilities: Building, calendar: CalendarDays };

function sectionFrom(resource: string) {
  return ['overview','organisation','academics','facilities','settings'].includes(resource) ? resource : 'overview';
}

function innerFrom(section: string) {
  if (section === 'organisation') return 'campuses';
  if (section === 'academics') return 'sessions';
  if (section === 'settings') return 'general';
  return section;
}

const Card: React.FC<React.PropsWithChildren<{ title?: string; action?: React.ReactNode }>> = ({ title, action, children }) => <section className="rounded-2xl border border-slate-200 bg-white shadow-xs">{(title || action) && <header className="flex items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><h3 className="text-sm font-bold text-slate-900">{title}</h3>{action}</header>}{children}</section>;
const Empty = ({ label }: { label?: string }) => <div className="px-5 py-10 text-center"><p className="text-sm font-semibold text-slate-700">No {String(label || 'records').toLowerCase()} yet</p><p className="mt-1 text-xs text-slate-400">Add the first record when you are ready.</p></div>;

export const SchoolStructureView: React.FC<Props> = ({ resource }) => {
  const { showToast } = useApp();
  const section = sectionFrom(resource);
  const [data, setData] = useState<Record<string, Row[]>>({});
  const [profile, setProfile] = useState<Row>({});
  const [inner, setInner] = useState(() => innerFrom(section));
  const [modal, setModal] = useState<string | null>(null);
  const [drawer, setDrawer] = useState<'profile' | 'row' | null>(null);
  const [selected, setSelected] = useState<Row | null>(null);
  const [form, setForm] = useState<Row>({});
  const [busy, setBusy] = useState(false);
  const [query, setQuery] = useState('');

  const load = useCallback(async () => {
    const getStructure = async (key: StructureKey) => { try { const r = await apiRequest<{ data: any }>(`/school-structure/${key}`, { suppressErrorNotification: true }); return r.data?.data ?? []; } catch { return []; } };
    const getModule = async (key: ModuleKey) => { try { const r = await apiRequest<{ data: any }>(`/school-modules/${key}`, { suppressErrorNotification: true }); return r.data?.data ?? []; } catch { return []; } };
    try { const r = await apiRequest<{ data: Row }>('/school-structure/profile', { suppressErrorNotification: true }); setProfile(r.data || {}); } catch (e) { showToast('School', describeApiError(e), 'error'); }
    const results = await Promise.all([...structureKeys.map(getStructure), ...(['houses','facilities','calendar'] as ModuleKey[]).map(getModule)]);
    setData(Object.fromEntries(allKeys.map((key, i) => [key, results[i]])));
  }, [showToast]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { setInner(innerFrom(section)); }, [section]);
  // #region agent log
  // #endregion
  const openCreate = (key: string) => { setSelected(null); setForm({}); setModal(key); };
  const openEdit = (key: string, row: Row) => { setSelected({ ...row, _key: key }); setForm({ ...row, ...(row.payload || {}) }); setDrawer('row'); };
  const save = async () => {
    const key = modal || selected?._key; if (!key) return; setBusy(true);
    try {
      if (structureKeys.includes(key as StructureKey) || key === 'terms') {
        const body = key === 'sessions' && !selected ? { ...form, terms: [{ name: 'First Term', sequence: 1, startsAt: form.startsAt, endsAt: form.endsAt }] } : form;
        await apiMutation(`/school-structure/${key}${selected?.id ? `/${selected.id}` : ''}`, selected?.id ? 'PATCH' : 'POST', body);
      } else {
        const body = { title: form.title || form.name || 'Untitled', status: form.status || 'active', payload: form };
        await apiMutation(`/school-modules/${key}${selected?.id ? `/${selected.id}` : ''}`, selected?.id ? 'PATCH' : 'POST', body);
      }
      showToast('Saved', `${labels[key]} updated.`, 'success'); setModal(null); setDrawer(null); setSelected(null); await load();
    } catch (e) { showToast('Could not save', describeApiError(e), 'error'); } finally { setBusy(false); }
  };
  const saveProfile = async () => { setBusy(true); try { await apiMutation('/school-structure/profile/profile', 'PATCH', form); setProfile(form); setDrawer(null); showToast('Saved', 'School profile updated.', 'success'); } catch (e) { showToast('Could not save', describeApiError(e), 'error'); } finally { setBusy(false); } };

  const currentSession = (data.sessions || []).find((r) => r.isCurrent) || data.sessions?.[0];
  const currentTerm = currentSession?.terms?.find((r: Row) => r.isCurrent) || currentSession?.terms?.[0];
  const progress = useMemo(() => { if (!currentTerm?.startsAt || !currentTerm?.endsAt) return null; const start = +new Date(currentTerm.startsAt), end = +new Date(currentTerm.endsAt); return end > start ? Math.max(0, Math.min(100, Math.round((Date.now() - start) / (end - start) * 100))) : null; }, [currentTerm]);

  const Table = ({ kind, limit }: { kind: string; limit?: number }) => {
    const label = labels[kind];
    // #region agent log
    // #endregion
    if (!label) return null;
    const source = (data[kind] || []).filter(Boolean).filter((row) => String(JSON.stringify(row) ?? '').toLowerCase().includes(String(query || '').toLowerCase()));
    const rows = source.slice(0, limit); const Icon = icons[kind] || School;
    const detailHead = kind === 'classes' ? 'Stream / capacity' : kind === 'sessions' ? 'Session dates' : kind === 'facilities' ? 'Type / campus' : kind === 'calendar' ? 'Date / category' : 'Code / details';
    return <Card title={label} action={<div className="flex items-center gap-2"><Button variant="outline" size="xs" leftIcon={<Download className="h-3.5 w-3.5" />} onClick={() => showToast('Export', 'Export will be available when the backend export endpoint is enabled.', 'info')}>Export</Button><Button size="xs" leftIcon={<Plus className="h-3.5 w-3.5" />} onClick={() => openCreate(kind)}>Add</Button></div>}>
      {!limit && <div className="flex flex-col gap-2 border-b border-slate-100 p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={`Search ${label.toLowerCase()}…`} className="h-9 w-full rounded-xl border border-slate-200 pl-9 pr-3 text-xs outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100" /></label><Button variant="outline" size="sm" leftIcon={<Filter className="h-3.5 w-3.5" />}>Filters</Button></div>}
      {rows.length === 0 ? <Empty label={label} /> : <div className="overflow-x-auto"><table className="w-full min-w-[640px] text-xs"><thead className="bg-slate-50/80 text-left text-slate-500"><tr><th className="px-5 py-3 font-semibold">Name</th><th className="px-4 py-3 font-semibold">{detailHead}</th><th className="px-4 py-3 font-semibold">Status</th><th className="px-4 py-3 text-right font-semibold">Actions</th></tr></thead><tbody>{rows.map((row, i) => <tr key={row.id || i} className="border-t border-slate-100 hover:bg-slate-50/70"><td className="px-5 py-3"><span className="flex items-center gap-2 font-semibold text-slate-800"><span className="grid h-7 w-7 place-items-center rounded-lg bg-indigo-50 text-indigo-600"><Icon className="h-3.5 w-3.5" /></span>{row.name || row.title}</span></td><td className="px-4 py-3 text-slate-500">{kind === 'classes' ? [row.arm, row.capacity && `Capacity ${row.capacity}`].filter(Boolean).join(' · ') || '—' : kind === 'sessions' ? [row.startsAt,row.endsAt].filter(Boolean).join(' – ') || '—' : [row.code,row.payload?.type,row.payload?.campus,row.payload?.date,row.arm].filter(Boolean).join(' · ') || '—'}</td><td className="px-4 py-3"><StatusBadge status={row.status || (row.isCurrent ? 'Active' : 'Active')} /></td><td className="px-4 py-3 text-right"><button aria-label={kind === 'sessions' ? `Add term to ${row.name}` : `Edit ${row.name || row.title}`} onClick={() => kind === 'sessions' ? (setForm({ sessionId: row.id }), setModal('terms')) : openEdit(kind, row)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><MoreHorizontal className="h-4 w-4" /></button></td></tr>)}</tbody></table></div>}
      {!limit && source.length > 0 && <footer className="border-t border-slate-100 bg-slate-50/50 px-5 py-3 text-[11px] text-slate-500">Showing {source.length} tenant-scoped record{source.length === 1 ? '' : 's'}</footer>}
    </Card>;
  };
  const tabs = section === 'organisation' ? [['campuses','Campuses'],['departments','Departments'],['houses','Houses']] : section === 'academics' ? [['sessions','Academic year'],['classes','Classes & streams'],['subjects','Subjects'],['calendar','Calendar']] : section === 'settings' ? [['general','General'],['branding','Branding'],['regional','Regional'],['defaults','Defaults']] : [];

  return <div className="mx-auto w-full max-w-[1600px] space-y-4 px-4 py-5 sm:px-6 lg:px-8">
    {tabs.length > 0 && <div className="flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-1">{tabs.map(([id,label]) => <button key={id} onClick={() => setInner(id)} className={`shrink-0 rounded-lg px-3.5 py-2 text-xs font-semibold ${inner === id ? 'bg-indigo-600 text-white shadow-xs' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800'}`}>{label}</button>)}</div>}
    {section === 'overview' && <>
      <div className="grid gap-4 lg:grid-cols-[1.35fr_.95fr_.95fr]">
        <Card title="School profile" action={<Button variant="ghost" size="xs" leftIcon={<Pencil className="h-3.5 w-3.5" />} onClick={() => { setForm(profile); setDrawer('profile'); }}>Edit profile</Button>}><div className="flex gap-4 p-5"><BrandMark variant="tenant" tenantName={profile.name || 'School'} tenantLogoUrl={profile.logoUrl} showText={false} size="xl" /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-950">{profile.name || 'School profile'}</h3><StatusBadge status={profile.status || 'Active'} /></div><p className="mt-1 text-xs font-semibold text-indigo-600">{profile.code || 'No school code'}</p><div className="mt-3 space-y-1.5 text-xs text-slate-500">{(profile.address || profile.city || profile.state) && <p className="flex gap-2"><MapPin className="h-3.5 w-3.5" />{[profile.address,profile.city,profile.state].filter(Boolean).join(', ')}</p>}{profile.email && <p className="flex gap-2"><Mail className="h-3.5 w-3.5" />{profile.email}</p>}{profile.phone && <p className="flex gap-2"><Phone className="h-3.5 w-3.5" />{profile.phone}</p>}</div>{profile.motto && <p className="mt-3 text-xs italic text-slate-500">“{profile.motto}”</p>}</div></div></Card>
        <Card title="Current academic session"><div className="p-5">{currentSession ? <><div className="flex items-center justify-between"><p className="text-2xl font-extrabold text-slate-950">{currentSession.name}</p><StatusBadge status={currentSession.status || 'Active'} /></div><p className="mt-3 text-sm font-semibold text-slate-700">{currentTerm?.name || 'No current term'}</p><p className="mt-1 text-xs text-slate-500">{currentTerm?.startsAt && currentTerm?.endsAt ? `${new Date(currentTerm.startsAt).toLocaleDateString()} – ${new Date(currentTerm.endsAt).toLocaleDateString()}` : 'Term dates not configured'}</p>{progress !== null && <><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${progress}%` }} /></div><p className="mt-2 text-[11px] font-semibold text-emerald-700">{progress}% of term elapsed</p></>}</> : <Empty label="academic sessions" />}</div></Card>
        <Card title="Academic structure"><div className="divide-y divide-slate-100">{[['campuses','Campuses'],['departments','Departments'],['classes','Classes'],['arms','Streams'],['subjects','Subjects']].map(([key,label]) => <div key={key} className="flex items-center justify-between px-5 py-2.5 text-xs"><span className="font-semibold text-slate-700">{label}</span><span className="font-bold text-slate-950">{(data[key] || []).length}</span></div>)}</div></Card>
      </div>
      <div className="grid gap-4 lg:grid-cols-[1.1fr_1fr]"><Table kind="campuses" limit={4} /><Table kind="calendar" limit={4} /></div>
      <div className="grid gap-4 lg:grid-cols-[1.25fr_.95fr_.95fr]">
        <Card title="Quick actions"><div className="grid grid-cols-2 gap-2 p-4 sm:grid-cols-4 lg:grid-cols-2 xl:grid-cols-4">{[['campuses','Add campus'],['departments','Add department'],['classes','Add class'],['subjects','Add subject'],['sessions','New session'],['facilities','Add facility']].map(([key,label]) => { const Icon=icons[key]; return <button key={key} onClick={() => openCreate(key)} className="flex min-h-20 flex-col items-center justify-center gap-2 rounded-xl border border-slate-200 text-xs font-semibold text-slate-700 hover:border-indigo-200 hover:bg-indigo-50/50 hover:text-indigo-700"><Icon className="h-5 w-5 text-indigo-600" />{label}</button>; })}</div></Card>
        <Card title="Recent activities"><Empty label="recent activities" /></Card>
        <Card title="Important alerts"><div className="p-4"><div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><p className="text-xs font-semibold text-slate-700">No active alerts</p><p className="mt-1 text-[11px] text-slate-400">Nothing requires attention right now.</p></div></div></Card>
      </div>
    </>}
    {section === 'organisation' && <div className="space-y-4">
      <SectionIntro icon={inner === 'campuses' ? Building2 : inner === 'departments' ? Network : Shield} title={labels[inner]} description={inner === 'campuses' ? 'Manage school locations and campus records.' : inner === 'departments' ? 'Organise subjects, classes and staff into departments.' : 'Manage student houses and their assigned leaders.'} count={(data[inner] || []).length} />
      {inner !== 'houses' && labels[inner] ? <Table kind={inner} /> : inner === 'houses' ? <><div className="flex justify-end"><Button leftIcon={<Plus className="h-4 w-4" />} size="sm" onClick={() => openCreate('houses')}>Add house</Button></div>{data.houses?.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.houses.map((house,i) => <Card key={house.id || i}><div className="p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Shield className="h-5 w-5" /></span><button onClick={() => openEdit('houses',house)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><MoreHorizontal className="h-4 w-4" /></button></div><h3 className="mt-4 text-sm font-bold text-slate-900">{house.title || house.name}</h3><p className="mt-1 text-xs text-slate-500">{house.payload?.houseMaster || 'No house master assigned'}</p><div className="mt-4 flex items-center justify-between"><StatusBadge status={house.status || 'Active'} /><span className="text-[11px] text-slate-400">{house.payload?.studentCount ?? '—'} students</span></div></div></Card>)}</div> : <Card><Empty label="houses" /></Card>}</> : null}
    </div>}
    {section === 'academics' && inner === 'sessions' && <div className="space-y-4"><SectionIntro icon={CalendarRange} title="Academic year" description="Manage sessions and the terms nested within each session." count={(data.sessions || []).length} /><Table kind="sessions" />{(data.sessions || []).map((s,i) => <Card key={s.id || i} title={s.name} action={<div className="flex gap-2">{s.isCurrent && <StatusBadge status="Active" />}<Button size="xs" variant="outline" onClick={() => { setForm({ sessionId: s.id }); setModal('terms'); }}>Add term</Button></div>}><div className="p-4">{s.terms?.length ? <div className="grid gap-2 sm:grid-cols-3">{s.terms.map((t:Row,j:number) => <button onClick={() => openEdit('terms',t)} key={t.id||j} className="rounded-xl border border-slate-200 p-3 text-left hover:border-indigo-200"><div className="flex items-center justify-between"><p className="text-xs font-bold text-slate-800">{t.name}</p>{t.isCurrent && <StatusBadge status="Active" />}</div><p className="mt-2 text-[11px] text-slate-500">{t.startsAt || '—'} – {t.endsAt || '—'}</p></button>)}</div> : <p className="text-xs text-slate-400">No terms configured for this session.</p>}</div></Card>)}</div>}
    {section === 'academics' && inner === 'classes' && <div className="space-y-4"><SectionIntro icon={UsersRound} title="Classes & streams" description="Classes and their streams are managed together in one workspace." count={(data.classes || []).length} /><div className="grid gap-3 sm:grid-cols-3"><MiniMetric label="Classes" value={(data.classes || []).length} /><MiniMetric label="Configured streams" value={(data.arms || []).length} /><MiniMetric label="Total capacity" value={(data.classes || []).reduce((n,r) => n + Number(r.capacity || 0), 0) || '—'} /></div><Table kind="classes" /></div>}
    {section === 'academics' && inner === 'subjects' && <div className="space-y-4"><SectionIntro icon={BookOpen} title="Subjects" description="Manage curriculum subjects and their codes." count={(data.subjects || []).length} /><Table kind="subjects" /></div>}
    {section === 'academics' && inner === 'calendar' && <div className="space-y-4"><SectionIntro icon={CalendarDays} title="Academic calendar" description="Term dates, examinations, holidays and school events." count={(data.calendar || []).length} /><div className="flex flex-wrap justify-between gap-2"><div className="flex rounded-xl border border-slate-200 bg-white p-1">{['Agenda','Month','Term'].map((view) => <button key={view} className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${view === 'Agenda' ? 'bg-indigo-600 text-white' : 'text-slate-500'}`}>{view}</button>)}</div><Button size="sm" leftIcon={<Plus className="h-4 w-4" />} onClick={() => openCreate('calendar')}>Add event</Button></div>{data.calendar?.length ? <div className="space-y-2">{data.calendar.map((event,i) => <Card key={event.id || i}><button onClick={() => openEdit('calendar',event)} className="flex w-full items-center gap-4 p-4 text-left"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-indigo-50 text-center text-xs font-bold text-indigo-700">{event.payload?.date ? new Date(event.payload.date).toLocaleDateString(undefined,{month:'short',day:'2-digit'}) : <CalendarDays className="h-5 w-5" />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-slate-900">{event.title}</span><span className="mt-1 block text-xs text-slate-500">{[event.payload?.scope,event.payload?.category].filter(Boolean).join(' · ') || 'School-wide event'}</span></span><StatusBadge status={event.status || 'Scheduled'} /></button></Card>)}</div> : <Card><Empty label="calendar events" /></Card>}</div>}
    {section === 'facilities' && <div className="space-y-4"><SectionIntro icon={Building} title="Facilities" description="Track spaces, capacity, campus assignment and availability." count={(data.facilities || []).length} /><div className="grid gap-3 sm:grid-cols-3"><MiniMetric label="Total facilities" value={(data.facilities || []).length} /><MiniMetric label="Available" value={(data.facilities || []).filter((r) => (r.status || '').toLowerCase() === 'active').length} /><MiniMetric label="Recorded capacity" value={(data.facilities || []).reduce((n,r) => n + Number(r.payload?.capacity || 0),0) || '—'} /></div><Table kind="facilities" /></div>}
    {section === 'settings' && inner === 'general' && <div className="grid gap-4 lg:grid-cols-[1fr_.75fr]"><Card title="School information" action={<Button size="xs" leftIcon={<Pencil className="h-3.5 w-3.5" />} onClick={() => { setForm(profile); setDrawer('profile'); }}>Edit</Button>}><div className="grid gap-x-8 gap-y-5 p-5 sm:grid-cols-2">{[['School name',profile.name],['School code',profile.code],['Email',profile.email],['Phone',profile.phone],['Address',[profile.address,profile.city,profile.state].filter(Boolean).join(', ')],['Motto',profile.motto]].map(([label,value]) => <div key={label}><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-medium text-slate-800">{value || 'Not configured'}</p></div>)}</div></Card><Card title="Profile status"><div className="p-5"><BrandMark variant="tenant" tenantName={profile.name || 'School'} tenantLogoUrl={profile.logoUrl} /><div className="mt-5 flex items-center justify-between"><span className="text-xs text-slate-500">Workspace status</span><StatusBadge status={profile.status || 'Active'} /></div></div></Card></div>}
    {section === 'settings' && inner === 'branding' && <BrandingStudio />}
    {section === 'settings' && inner === 'regional' && <div className="grid gap-4 lg:grid-cols-2"><Card title="Region and time"><div className="space-y-4 p-5"><Field name="country" value={profile.country || ''} onChange={() => undefined} disabled /><Field name="timezone" value={profile.timezone || ''} onChange={(value) => setProfile((p) => ({...p,timezone:value}))} /><p className="text-[11px] text-slate-400">Country is controlled by tenant provisioning. Timezone can be changed from Edit school information.</p><Button size="sm" onClick={() => { setForm(profile); setDrawer('profile'); }}>Update timezone</Button></div></Card><Card title="Display preferences"><div className="space-y-5 p-5">{[['Currency',profile.currency],['Language','English'],['Date format','Locale default']].map(([label,value]) => <div key={label} className="flex items-center justify-between border-b border-slate-100 pb-4 text-xs"><span className="text-slate-500">{label}</span><span className="font-semibold text-slate-800">{value || 'Not configured'}</span></div>)}</div></Card></div>}
    {section === 'settings' && inner === 'defaults' && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><DefaultCard title="Default campus" value={data.campuses?.[0]?.name || 'Not configured'} detail="Used when a campus is not explicitly selected." /><DefaultCard title="Current academic session" value={currentSession?.name || 'Not configured'} detail="Derived from the active academic session." /><DefaultCard title="Attendance configuration" value="Workspace default" detail="No tenant-specific override is currently configured." /></div>}

    <Modal isOpen={!!modal} onClose={() => setModal(null)} title={modal ? `Add ${labels[modal]?.replace(/s$/, '') || 'record'}` : ''} description="Create a tenant-scoped record." footer={<><Button variant="outline" onClick={() => setModal(null)}>Cancel</Button><Button isLoading={busy} onClick={save}>Create</Button></>}><div className="grid gap-4 sm:grid-cols-2">{modal && (fields[modal] || ['name']).map((field) => <Field key={field} name={field} value={form[field] || ''} onChange={(value) => setForm((v) => ({...v,[field]:value}))} />)}</div></Modal>
    <Drawer isOpen={drawer === 'profile'} onClose={() => setDrawer(null)} title="Edit school profile" description="Update the school identity and contact details." footer={<><Button variant="outline" onClick={() => setDrawer(null)}>Cancel</Button><Button isLoading={busy} onClick={saveProfile}>Save changes</Button></>}><div className="space-y-4">{['name','motto','address','city','state','email','phone','timezone'].map((field) => <Field key={field} name={field} value={form[field] || ''} onChange={(value) => setForm((v) => ({...v,[field]:value}))} />)}</div></Drawer>
    <Drawer isOpen={drawer === 'row'} onClose={() => setDrawer(null)} title={`Edit ${selected ? labels[selected._key] : 'record'}`} footer={<><Button variant="outline" onClick={() => setDrawer(null)}>Cancel</Button><Button isLoading={busy} onClick={save}>Save changes</Button></>}><div className="space-y-4">{selected && (fields[selected._key] || ['name']).map((field) => <Field key={field} name={field} value={form[field] ?? ''} onChange={(value) => setForm((v) => ({...v,[field]:value}))} />)}</div></Drawer>
  </div>;
};

const Field = ({ name, value, onChange, disabled = false }: { key?: React.Key; name: string; value: string | number; onChange: (value: string) => void; disabled?: boolean }) => <label className="block text-xs font-semibold capitalize text-slate-700">{name.replace(/([A-Z])/g,' $1')}<input disabled={disabled} type={name.toLowerCase().includes('date') || name === 'date' ? 'date' : name === 'capacity' ? 'number' : 'text'} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 disabled:bg-slate-50 disabled:text-slate-400" /></label>;

const SectionIntro = ({ icon: Icon, title, description, count }: { icon: React.ElementType; title: string; description: string; count: number }) => <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-xs sm:flex-row sm:items-center"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><h2 className="text-base font-bold text-slate-900">{title}</h2><p className="mt-0.5 text-xs text-slate-500">{description}</p></div><span className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600">{count} total</span></div>;

const MiniMetric = ({ label, value }: { label: string; value: React.ReactNode }) => <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-xs"><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-xl font-extrabold text-slate-950">{value}</p></div>;

const DefaultCard = ({ title, value, detail }: { title: string; value: string; detail: string }) => <Card><div className="p-5"><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Settings2 className="h-4 w-4" /></span><StatusBadge status={value === 'Not configured' ? 'Inactive' : 'Active'} /></div><h3 className="mt-4 text-sm font-bold text-slate-900">{title}</h3><p className="mt-1 text-sm font-semibold text-indigo-700">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></div></Card>;
