import React, { useMemo, useState } from 'react';
import { BookOpen, GraduationCap, MoreHorizontal, Search, Send, ShieldCheck, Upload, UserPlus, Users } from 'lucide-react';
import { Button, DataTable, Drawer, FormField, Input, MetricCard, Modal, Select, StatusBadge, type Column } from '../../../components/ui';
import { useApp } from '../../../context/AppContext';
import { ListPageLayout } from '../../../layouts/ListPageLayout';
import type { StaffMember } from '../../../types';

export const WorkforcePage: React.FC<{ view?: 'staff' | 'teachers' }> = ({ view = 'staff' }) => {
  const { staff, inviteStaff, showToast } = useApp();
  const [query, setQuery] = useState('');
  const [selectedRole, setSelectedRole] = useState('ALL');
  const [selected, setSelected] = useState<StaffMember | null>(null);
  const [modal, setModal] = useState<'create' | 'invite' | 'import' | null>(null);
  const [form, setForm] = useState({ fullName: '', email: '', phone: '+234 ', role: 'Teacher' });
  const workforce = useMemo(() => staff.filter((member) => view !== 'teachers' || member.role.toLowerCase().includes('teacher')), [staff, view]);
  const filtered = useMemo(() => workforce.filter((member) => `${member.fullName} ${member.email} ${member.role}`.toLowerCase().includes(query.trim().toLowerCase()) && (selectedRole === 'ALL' || member.role === selectedRole)), [workforce, query, selectedRole]);
  const roles = [...new Set(workforce.map((member) => member.role))];
  const submit = (event: React.FormEvent) => { event.preventDefault(); inviteStaff({ ...form, subjects: [], assignedClasses: [] }); showToast(modal === 'invite' ? 'Invitation sent' : 'Workforce profile created', `${form.fullName} was added to the workforce.`, 'success'); setModal(null); setForm({ fullName: '', email: '', phone: '+234 ', role: 'Teacher' }); };
  const columns: Column<StaffMember>[] = [
    { key: 'name', header: 'Workforce member', sortable: true, sortValue: (member) => member.fullName, accessor: (member) => <div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[var(--primitive-indigo-50)] text-xs font-semibold text-[var(--color-action-primary)]">{member.fullName.slice(0, 2).toUpperCase()}</span><span><span className="block font-semibold text-[var(--color-text-primary)]">{member.fullName}</span><span className="block text-xs text-[var(--color-text-muted)]">{member.email}</span></span></div> },
    { key: 'staffNo', header: 'Staff No.', accessor: (member) => member.staffNo || '—' },
    { key: 'role', header: 'Role', sortable: true, sortValue: (member) => member.role, accessor: (member) => member.role },
    { key: 'campus', header: 'Campus', accessor: (member) => member.campus || '—' },
    { key: 'status', header: 'Status', accessor: (member) => <StatusBadge status={member.status === 'Pending Invitation' ? 'Pending' : member.status} /> },
    { key: 'actions', header: <span className="sr-only">Actions</span>, align: 'right', accessor: (member) => <Button variant="ghost" size="icon-sm" aria-label={`Open ${member.fullName}`} onClick={(event) => { event.stopPropagation(); setSelected(member); }}><MoreHorizontal className="h-4 w-4" /></Button> },
  ];
  const teacherCount = staff.filter((member) => member.role.toLowerCase().includes('teacher')).length;
  const metrics = <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={view === 'teachers' ? 'Total Teachers' : 'Total Workforce'} value={workforce.length} icon={<Users className="h-5 w-5" />} subtitle="School personnel" /><MetricCard label="Active Members" value={workforce.filter((member) => member.status === 'Active').length} icon={<ShieldCheck className="h-5 w-5" />} variant="success" subtitle="Active school access" /><MetricCard label="Teaching Staff" value={teacherCount} icon={<BookOpen className="h-5 w-5" />} variant="primary" subtitle="Teaching functions" /><MetricCard label="Pending Invites" value={workforce.filter((member) => member.status === 'Pending Invitation').length} icon={<Send className="h-5 w-5" />} variant="warning" subtitle="Awaiting sign-up" /></div>;
  const toolbar = <div className="flex flex-col gap-3 border-b border-[var(--color-border-default)] p-4 lg:flex-row lg:items-center"><label className="relative min-w-60 flex-1"><span className="sr-only">Search workforce</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--color-text-muted)]" /><input className="ds-field-control pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name, email, or role" /></label><Select className="lg:w-48" aria-label="Filter by role" value={selectedRole} onChange={(event) => setSelectedRole(event.target.value)}><option value="ALL">All roles</option>{roles.map((item) => <option key={item} value={item}>{item}</option>)}</Select><div className="flex gap-2 lg:ml-auto"><Button variant="outline" leftIcon={<Upload className="h-4 w-4" />} onClick={() => setModal('import')}>Import</Button><Button variant="outline" leftIcon={<Send className="h-4 w-4" />} onClick={() => setModal('invite')}>Invite</Button></div></div>;
  const title = view === 'teachers' ? 'Teachers' : 'Workforce';
  return <>
    <ListPageLayout breadcrumb={[{ label: 'People' }, { label: title }]} title={title} description={view === 'teachers' ? 'Manage workforce members with teaching functions and assignments.' : 'Manage employees, roles, and school access.'} action={<Button leftIcon={<UserPlus className="h-4 w-4" />} onClick={() => setModal('create')}>Add Workforce Member</Button>} metrics={metrics} toolbar={toolbar}>
      <DataTable columns={columns} data={filtered} keyExtractor={(member) => member.id} pageSize={10} onRowClick={setSelected} emptyTitle={query || selectedRole !== 'ALL' ? 'No matching workforce members' : 'No workforce members yet'} emptyDescription={query || selectedRole !== 'ALL' ? 'Try adjusting your filters.' : 'Add a workforce member to begin.'} mobileRenderer={(member) => <button type="button" className="ds-focus-ring w-full p-4 text-left" onClick={() => setSelected(member)}><span className="flex items-center justify-between gap-3"><strong>{member.fullName}</strong><StatusBadge status={member.status === 'Pending Invitation' ? 'Pending' : member.status} /></span><span className="mt-2 block text-xs text-[var(--color-text-secondary)]">{member.role} · {member.staffNo || 'No staff number'}</span></button>} />
    </ListPageLayout>
    <Modal isOpen={modal === 'create' || modal === 'invite'} onClose={() => setModal(null)} title={modal === 'invite' ? 'Invite Workforce Member' : 'Add Workforce Member'} description="Create a workforce profile and school access."><form onSubmit={submit} className="space-y-4"><FormField label="Full name" required><Input required value={form.fullName} onChange={(event) => setForm({ ...form, fullName: event.target.value })} /></FormField><FormField label="Email address" required><Input type="email" required value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></FormField><FormField label="Phone number"><Input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></FormField><FormField label="Role"><Select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option>Teacher</option><option>Principal</option><option>Exam Officer</option><option>Bursar</option></Select></FormField><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setModal(null)}>Cancel</Button><Button type="submit">{modal === 'invite' ? 'Send Invitation' : 'Add Member'}</Button></div></form></Modal>
    <Modal isOpen={modal === 'import'} onClose={() => setModal(null)} title="Import Workforce" description="Upload a CSV using the school workforce template."><label className="flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-[var(--radius-card)] border border-dashed border-[var(--color-border-strong)] p-6 text-center"><Upload className="h-6 w-6 text-[var(--color-action-primary)]" /><span className="mt-2 text-sm font-semibold">Choose CSV file</span><input type="file" accept=".csv,text/csv" className="sr-only" onChange={() => { setModal(null); showToast('Import queued', 'Workforce file is ready for validation.', 'success'); }} /></label></Modal>
    <Drawer isOpen={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.fullName} description={selected?.role}>{selected && <div className="space-y-3 text-sm"><p>{selected.email}</p><p>{selected.phone}</p><p>{selected.campus || 'No campus assigned'}</p><StatusBadge status={selected.status === 'Pending Invitation' ? 'Pending' : selected.status} /></div>}</Drawer>
  </>;
};
