import React, { useEffect, useMemo, useState } from 'react';
import { Eye, Mail, Phone, Search, Send, Upload, UserPlus, Users, UserCheck, Link2, MoreHorizontal } from 'lucide-react';
import { apiMutation, apiRequest, describeApiError } from '../../lib/apiClient';
import { useApp } from '../../context/AppContext';
import { Button, DataTable, Drawer, FormField, Input, MetricCard, Modal, StatusBadge, type Column } from '../../components/ui';

interface GuardianRow { id: string; name: string; email?: string; phone?: string; students: string[] }

export const ParentsView: React.FC = () => {
  const { showToast } = useApp();
  const [rows, setRows] = useState<GuardianRow[]>([]);
  const [query, setQuery] = useState('');
  const [form, setForm] = useState({ name: '', email: '', phone: '' });
  const [modal, setModal] = useState<'add' | 'invite' | 'import' | null>(null);
  const [selected, setSelected] = useState<GuardianRow | null>(null);
  const [busy, setBusy] = useState(false);
  const load = () => apiRequest<{ success: true; data: { data: GuardianRow[] } }>('/guardians', { suppressErrorNotification: true }).then((response) => setRows(response.data.data || [])).catch((error) => showToast('Parents', describeApiError(error), 'error'));
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => rows.filter((row) => `${row.name} ${row.email || ''} ${row.phone || ''} ${(row.students || []).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  const linked = rows.filter((row) => row.students?.length).length;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await apiMutation('/guardians', 'POST', form); showToast(modal === 'invite' ? 'Invitation sent' : 'Guardian saved', `${form.name} was added to this school.`, 'success'); setForm({ name: '', email: '', phone: '' }); setModal(null); load(); } catch (error) { showToast('Could not save', describeApiError(error), 'error'); } finally { setBusy(false); } };
  const columns: Column<GuardianRow>[] = [
    { key: 'name', header: 'Parent / Guardian', sortable: true, accessor: (row) => <div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-xl bg-indigo-50 text-xs font-bold text-indigo-700">{row.name.slice(0,2).toUpperCase()}</span><div><p className="font-semibold text-slate-900">{row.name}</p><p className="text-[11px] text-slate-400">Guardian account</p></div></div> },
    { key: 'contact', header: 'Contact', accessor: (row) => <div className="space-y-1 text-xs text-slate-600"><p>{row.email || 'No email'}</p><p>{row.phone || 'No phone'}</p></div> },
    { key: 'students', header: 'Linked students', accessor: (row) => row.students?.length ? <div className="flex flex-wrap gap-1">{row.students.slice(0,2).map((name) => <span key={name} className="rounded-md bg-slate-100 px-2 py-1 text-[10px] font-medium">{name}</span>)}</div> : <span className="text-slate-400">Not linked</span> },
    { key: 'status', header: 'Status', accessor: (row) => <StatusBadge status={row.email ? 'Active' : 'Pending'} /> },
    { key: 'actions', header: '', align: 'right', accessor: (row) => <button onClick={(e) => { e.stopPropagation(); setSelected(row); }} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><MoreHorizontal className="h-4 w-4" /></button> },
  ];
  return <div className="space-y-6">
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><MetricCard label="Total Guardians" value={rows.length} icon={<Users className="h-5 w-5" />} subtitle="Family contacts" /><MetricCard label="Linked Guardians" value={linked} icon={<Link2 className="h-5 w-5" />} variant="success" subtitle="Connected to students" /><MetricCard label="Active Accounts" value={rows.filter((r) => r.email).length} icon={<UserCheck className="h-5 w-5" />} variant="primary" subtitle="Email access available" /><MetricCard label="Pending Setup" value={rows.filter((r) => !r.email).length} icon={<Mail className="h-5 w-5" />} variant="warning" subtitle="Missing account email" /></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xs"><div className="flex flex-col gap-3 border-b border-slate-100 bg-slate-50/40 p-4 lg:flex-row lg:items-center lg:justify-between"><label className="relative w-full lg:max-w-sm"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search guardians or linked students…" className="h-9 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-xs outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100" /></label><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" leftIcon={<Upload className="h-3.5 w-3.5" />} onClick={() => setModal('import')}>Bulk Import</Button><Button variant="outline" size="sm" leftIcon={<Send className="h-3.5 w-3.5" />} onClick={() => setModal('invite')}>Invite Guardian</Button><Button size="sm" leftIcon={<UserPlus className="h-3.5 w-3.5" />} onClick={() => setModal('add')}>Add Guardian</Button></div></div><DataTable columns={columns} data={filtered} keyExtractor={(row) => row.id} pageSize={10} onRowClick={setSelected} emptyTitle="No guardians found" emptyDescription="Add a guardian or adjust your search." className="border-none rounded-none shadow-none" /></section>
    <Modal isOpen={modal === 'add' || modal === 'invite'} onClose={() => setModal(null)} title={modal === 'invite' ? 'Invite Parent / Guardian' : 'Add Guardian'} description={modal === 'invite' ? 'Create a guardian record and send family access.' : 'Add a family contact to the school.'}><form onSubmit={submit} className="space-y-4"><FormField label="Full name" required><Input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} /></FormField><FormField label="Email address" required={modal === 'invite'}><Input type="email" required={modal === 'invite'} value={form.email} onChange={(e) => setForm({...form,email:e.target.value})} /></FormField><FormField label="Phone number"><Input value={form.phone} onChange={(e) => setForm({...form,phone:e.target.value})} /></FormField><div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><Button variant="outline" onClick={() => setModal(null)}>Cancel</Button><Button type="submit" isLoading={busy}>{modal === 'invite' ? 'Send Invitation' : 'Add Guardian'}</Button></div></form></Modal>
    <Modal isOpen={modal === 'import'} onClose={() => setModal(null)} title="Bulk Import Parents / Guardians" description="Upload family contacts using the guardian CSV template."><div className="rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50/60 p-8 text-center"><Upload className="mx-auto h-7 w-7 text-indigo-600" /><p className="mt-3 text-sm font-semibold text-slate-800">Choose CSV file or drag and drop</p><p className="mt-1 text-xs text-slate-400">Full name, email, phone and student admission number.</p><label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-semibold text-white"><Upload className="h-4 w-4" />Browse CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={() => { setModal(null); showToast('Import queued','Guardian file is ready for validation.','success'); }} /></label></div></Modal>
    <Drawer isOpen={!!selected} onClose={() => setSelected(null)} title={selected?.name} description="Guardian profile and linked students.">{selected && <div className="space-y-5"><div className="rounded-2xl border border-slate-200 p-4"><p className="flex items-center gap-2 text-sm text-slate-700"><Mail className="h-4 w-4 text-slate-400" />{selected.email || 'No email'}</p><p className="mt-3 flex items-center gap-2 text-sm text-slate-700"><Phone className="h-4 w-4 text-slate-400" />{selected.phone || 'No phone'}</p></div><div className="rounded-2xl border border-slate-200 p-4"><h4 className="text-xs font-bold uppercase tracking-wide text-slate-500">Linked students</h4><div className="mt-3 space-y-2">{selected.students?.length ? selected.students.map((student) => <div key={student} className="rounded-xl bg-slate-50 px-3 py-2 text-sm font-medium text-slate-800">{student}</div>) : <p className="text-xs text-slate-400">No students linked.</p>}</div></div></div>}</Drawer>
  </div>;
};
